name: Auto-Merge Changelog PR

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'autorelease: tagged') && contains(github.event.pull_request.title, 'chore(development):')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Auto merge changelog PRs
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin --repo ${{ github.repository }}
