name: Auto-Merge Changelog PR

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Enable auto-merge
        if: ${{ startsWith(github.event.pull_request.title, 'chore(development):') }}
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}

      - name: Auto merge changelog PRs
        if: ${{ startsWith(github.event.pull_request.title, 'chore(development):') }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin --repo ${{ github.repository }}
