name: Release Please

on:
  push:
    branches:
      - main
      - development

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, development]
    
    steps:
      - name: Checkout Repository
        uses: Fishbone-Aquatics/checkout@v3

      - name: Set up Node.js
        uses: Fishbone-Aquatics/setup-node@v3
        with:
          node-version: '14'

      - name: Release Please
        if: github.ref == 'refs/heads/${{ matrix.branch }}'
        uses: Fishbone-Aquatics/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: 'simple'
          target-branch: ${{ matrix.branch }}
